// Generated by CoffeeScript 1.7.1
(function() {
  var $, cname, debug, _,
    __slice = [].slice;

  _ = require("underscore");

  $ = require('jquery');

  debug = true;

  cname = ".d__panel";

  module.exports = function(opt) {
    var cssobj;
    cssobj = $.extend({
      position: "fixed",
      top: 0,
      right: 0,
      background: "#fff",
      opacity: 0.8,
      height: "100%",
      width: 300,
      "word-break": "break-all",
      overflow: "scroll"
    }, opt || {});
    return function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (!debug) {
        return;
      }
      if ($(cname).length < 1) {
        $("<div class='" + cname + "'>").css(cssobj).appendTo($("body"));
      }
      $("<pre style='color:blue'>").html("==== LOG ==== ").appendTo(cname);
      return _.map(args, function(e, i) {
        return $("<pre>").html(JSON.stringify(e, null, 2) + "<br>").appendTo(cname);
      });
    };
  };

}).call(this);
